version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "Account"
      MYSQL_PASSWORD: "root"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumns:
      - ~/Desktop/project/js/docker_test/mysql:/var/lib/mysql